### ISSUE TITLE
Request for LunarClient-Compatible GTB-Solver Weave Mod Version

### ISSUE THREAD

**Issue by muskf** [zSkillCode/gtb-solver#3]
### Issue Description
Firstly, thank you for your efforts on GTB-Solver. I have noticed that your Forge Mod is incredibly powerful, but unfortunately, it currently doesn't run on LunarClient. Therefore, I would like to request if you could develop a LunarClient-compatible GTB-Solver Weave Mod version.

### Background on LunarClient and Weave Mod
LunarClient is a popular Minecraft client optimization tool that provides players with various enhancements and optimizations. On the other hand, [Weave loader](https://github.com/Weave-MC/Weave-Loader) is a lightweight mod loader known for its fast, efficient, and stable mod support. Converting GTB-Solver into a Weave Mod will not only enable more players to use your mod on LunarClient but also provide better performance and stability.

### Request
Given your continued engagement with the project in the past, and your recent responses to issues, I sincerely hope that you will consider my request. In my view, making GTB-Solver compatible with LunarClient will benefit a larger audience and expand the reach of your project.

### Gratitude for Your Work
Once again, thank you for your contributions to the Minecraft community. Your efforts have allowed players to enjoy a richer gaming experience. I look forward to your thoughtful consideration of this request, and if you need any assistance or support, please feel free to reach out to me.

### Postscript
Regardless of whether you can fulfill this request, I hope you will continue to remain engaged with the project. Your experience and expertise are invaluable to the entire community. Thank you for taking the time to read my issue, and **I wish you all the best in your endeavors!**

**Comment by DavidNiessen** [comment]
Hi @muskf, thank you very much for your kind words, I really appreciate it!
Unfortunately, I'm not developing Minecraft mods anymore. 
If you know someone who would like to develop a lunar client version or would like to continue the project, feel free to send them the source code. Thank you!
