### ISSUE TITLE
Unused method

### ISSUE THREAD

**Issue by DqrkEvil** [zSkillCode/gtb-solver#4]
I've been trying to edit and build this mod so it automatically types the potentially correct words one by one with 3 seconds delay in chat for quite some time now but I never get any output in-game, today I noticed that at line 18 in the TickListener.java file the "onTick" method and "tickEvent" parameter are unused, does this have to do with me not getting any output when in a GTB game? If so, what can I do to resolve it.

**Comment by DavidNiessen** [comment]
Your ide probably marks the onTick method as unused because it is not invoked manually in this project (it is invoked by Forge).  The parameter is indeed unused, but that's because I had no use for it. I don't know why you get no output unfortunately.
